### PR TITLE
Test to check if journal gets written to disk

### PR DESCRIPTION
**Pull request by trishnaguha**
Test for journal https://github.com/kushaldas/tunirtests/issues/28

### CODE REVIEW

**Comment by kushaldas** [comment]
Can you please fix the merge conflicts?

**Comment by kushaldas** [comment]
Can you please give details about how to execute this test? Means should we execute it at first before any other test?

**Comment by trishnaguha** [comment]
Can you check http://fpaste.org/317887/ and http://fpaste.org/317888/ ? :)

If I remove the `if_rebooted()` condition the test will run okay for base image.
But if I remove the `if_rebooted()` condition the test will fail for atomic image. So i had to add `if_rebooted()` condition.

Now for base image the test will run after first reboot. The test will be skipped if reboot of the base image is not performed atleast for once.
But for atomic image the test will run after second reboot. The test will be skipped if reboot of the atomic image is not performed atleast for twice. 

Because the output of `journalctl --list-boot` for atomic image and base image are different on first and second reboot.
https://bugzilla.redhat.com/show_bug.cgi?id=1265295 also has the same output for atomic image.

**Comment by kushaldas** [comment]
So what atomic is doing is wrong, and that should fail. We have to test that behavior. Our goal is catch this issue :)

**Comment by nzwulfin** [comment]
Test instructions:
The current intent is to run the test after the first reboot, test should succeed.

Test targets:
Fedora-Cloud-Atomic-23-20160106.x86_64
Fedora-Cloud-Base-23-20151030.x86_64

Test outcomes:
Passes on Atomic host
Passes on Base host

LGTM. :+1:

**Comment by trishnaguha** [comment]
Cool thanks @nzwulfin :)

**Pull request merged**
